pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'wgsmus-recover' }
    stages {
        stage('Test') {
            options { timeout(time: 5, unit: 'MINUTES') }
            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test -Dgroups=integration'
                }
            }
        }
        stage('Build Image') {
            environment { QUAY = credentials('QUAY_USER') }
            steps {
                dir('shopping-cart-v2') {
                    sh './scripts/include-container-extensions.sh'
                    sh '''
                        ./scripts/build-and-push-image.sh \
                        -u $QUAY_USR \
                        -p $QUAY_PSW \
                        -b $BUILD_NUMBER
                    '''
                }
            }
        }
    }
}